"""Added bio, profile_picture and personal_details column to user

Revision ID: 74416ed08a0e
Revises: 64fc4c52825a
Create Date: 2024-10-12 07:48:59.216350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74416ed08a0e'
down_revision = '64fc4c52825a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('personal_details', sa.Text(), nullable=True))
        batch_op.alter_column('verification_token',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.String(length=128),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('personal_details')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
